### ISSUE TITLE
Using refined model

### ISSUE THREAD

**Issue by cbenitez81** [paTRICK-swk/P-STMO#1]
Hi thanks for the paper to start with.

I wondering about the refined model, it seems that needs the 3d ground truth to make the refinement and the camera parameters?. I was wondering if you obtained those automatically or it's kind of overfitting to the 3d ground-truth in some way

thanks

**Comment by paTRICK-swk** [comment]
You're right. It does lead to some degree of overfitting. On the other hand, the 3d ground-truth and camera parameters are not available when testing on custom videos, so the refining module does not work.

**Comment by vicentowang** [comment]
> You're right. It does lead to some degree of overfitting. On the other hand, the 3d ground-truth and camera parameters are not available when testing on custom videos, so the refining module does not work.

may it be possiable to use DNN( inpust_2d ) to predict a camera parameters for the wild video ?
camera parameters refer to f and c ?
