### ISSUE TITLE
Do I need to re-train the model in order to do causal prediction?

### ISSUE THREAD

**Issue by sylyt62** [paTRICK-swk/P-STMO#10]
I saw your discussion in #3 , I got a further question.

I implemented videopose3d as well, it takes (1, 100, 17, 2) as inputs and yields (1, 100, 17, 3), so I can just take the last (17, 3) as the 3d pose prediction in the lasted frame. (many to many)

However, your approach is padding a frame at two sides and predicting the middle frame (many to one), so do I need to train the network again to let it predict the last frame ( In causal case)?

Thank you in advance!

**Comment by paTRICK-swk** [comment]
Yes, you need to re-train the network in the causal case.
