### ISSUE TITLE
pre-trained file for stage 1

### ISSUE THREAD

**Issue by haofeng0705** [paTRICK-swk/P-STMO#14]
thanks for the great works!

can you please provide your_best_model_in_stage_I.pth for stage 1, the time for stage 1 training is too long.

**Comment by paTRICK-swk** [comment]
You can download the best P-STMO-S model (CPN, Stage I) on Human3.6M from [here](https://drive.google.com/file/d/1isWxrQyLV5wciGr3gsr3NhF9RV5s07YF/view?usp=sharing).

**Comment by haofeng0705** [comment]
thank you! btw, how can I save the predicted 3d poses and corresponding labels output from the model?

**Comment by paTRICK-swk** [comment]
You can use np.save to save the 3d poses. Labels: Root: 0  Left hip:1  Left knee:2  Left ankle:3  Right hip:4  Right knee:5 right ankle:6  Belly:7  neck:8  nose:9  head:10  right shoulder:11  right elbow:12  right hand:13  Left shoulder:  14  left elbow:15  left hand:  16
