### ISSUE TITLE
problems with multiple gpu

### ISSUE THREAD

**Issue by haofeng0705** [paTRICK-swk/P-STMO#15]
<img width="946" alt="image" src="https://user-images.githubusercontent.com/30925823/195269693-8be2d89e-c1ff-42d6-9e43-210ff5936aea.png">

I set batchsize = 640 for 4 gpus, but it shows above error

**Comment by paTRICK-swk** [comment]
Sorry, based on the information you provided, it's hard to tell where the problem lies. My guess is that when using multiple gpus for training, the mask is also split which leads to inconsistent dimensionality.
