### ISSUE TITLE
Multi-person Visualization

### ISSUE THREAD

**Issue by Songinpyo** [paTRICK-swk/P-STMO#19]
Hi,
First of all, thank you for the good research that inspires me.

I have a question about Multi-person video-to-pose.

I think P-STMO can estimate multi-person pose with yolo.

Is there a multi-person version video-to-pose code other than the existing single-person version?

I look forward to your response. Thank you!

**Comment by paTRICK-swk** [comment]
Sorry for the late reply. I don't have a multi-person version implemented at the moment. Referring to the top-down approaches for multi-person pose estimation, you can first extract the bounding box of a single person from the image, and then use the single-person pose estimation method.
