### ISSUE TITLE
run_in_wild.py fails at run time

### ISSUE THREAD

**Issue by liamsun2019** [paTRICK-swk/P-STMO#2]
Hi author,

Looks like options 'plot_MAE' and 'MAE_test_reload' are not defined in opt.py, which incur errors when running:

python run_in_the_wild.py -k detectron_pt_coco -f 243 -b 160 --MAE --train 1 --layers 3 -tds 2 -tmr 0.8 -smn 2 --lr 0.0001 -lrd 0.97

Should I just comment them or there's any better way to fix it? Thanks.

**Comment by paTRICK-swk** [comment]
Just comment them out. This bug has been fixed.

**Comment by liamsun2019** [comment]
Thanks for your quick fix.

**Comment by liamsun2019** [comment]
Another minor typo:
in_the_wild/arguments.py
parser.add_argument('--channle', default=256, type=int)
==> parser.add_argument('--channel', default=256, type=int)

The inference of videopose_PSTMO.py against wild videos will fail due to above typo.

**Comment by paTRICK-swk** [comment]
> Another minor typo: in_the_wild/arguments.py parser.add_argument('--channle', default=256, type=int) ==> parser.add_argument('--channel', default=256, type=int)
> 
> The inference of videopose_PSTMO.py against wild videos will fail due to above typo.

Thanks for your feedback. I will fix it.
