### ISSUE TITLE
How to estimate 3d pose using part of 2d key points?

### ISSUE THREAD

**Issue by mix0z** [paTRICK-swk/P-STMO#22]
Hi, is it possible to run model and render key points, using 2d pose with only part of key points(for cases when port of body is not visible and model for 2d HPE can't estimate some key points). I tried to use [-1, -1] or [nan, nan] for not visible key points but it doesn't work. Do you have any solution or maybe advices how I can solve this. Thanks!

**Comment by paTRICK-swk** [comment]
You can refer to the idea of padding embedding in this paper to replace the invisible 2D keypoints with a shared learnable 2D vector. This allows the network to adaptively recover 3D positions from these vectors.
