### ISSUE TITLE
About Cross-dataset Experimnts

### ISSUE THREAD

**Issue by wenwen12321** [paTRICK-swk/P-STMO#23]
Hi author,

Have you ever tried cross-dataset experiments where you pre-train and fine-tune on **Human3.6M** and then perform inference on **MPI-INF-3DHP**?

When I attempted this experiment, the results were unsatisfactory, with only a single point appearing in the visualization instead of a full 17 keypoints skeleton.

Could you please advise me on how to address this issue or provide suggestions on what approach to take?

Looking for your reply. Thank you very much.

**Comment by paTRICK-swk** [comment]
I have not tried it. Sorry for not being helpful.
