### ISSUE TITLE
parser.add_argument

### ISSUE THREAD

**Issue by jianlai123-123** [paTRICK-swk/P-STMO#24]
Hello, in the opt.py file, self.parser.add_ Argument ('-- MAE_test-reload', type=int, default=0) is missing. Is that right? Is default=0 or default=1? Looking forward to your reply, thank you.

**Comment by paTRICK-swk** [comment]
This was a parameter I used in the early stages of debugging the model, and its purpose was to validate the performance of Stage one. I removed it later when I was reorganizing the code. You don't need it for training and testing. The default value is 0.
