### ISSUE TITLE
Train and evaluate epoch

### ISSUE THREAD

**Issue by jianlai123-123** [paTRICK-swk/P-STMO#25]
Hello, pre training and formal training epoch=80. Do the two stages add up to 80? Or is it said that each stage is 80. How much should epoch be evaluated? Looking forward to your reply @paTRICK-swk

**Comment by paTRICK-swk** [comment]
The epoch of each stage is 80.

‘How much should epoch be evaluated?’ 
What's that supposed to mean?

**Comment by jianlai123-123** [comment]
Okay, thank you for your reply.
