### ISSUE TITLE
How AUC and PCK Calculate Values

### ISSUE THREAD

**Issue by jianlai123-123** [paTRICK-swk/P-STMO#26]
Hello author, thank you for your work. I would like to ask how to obtain a value for AUC and PCK in the paper, which are only one value. When I am running, they are the values of some columns.Is it the average value of the area circled in green?
<img width="606" alt="1" src="https://github.com/paTRICK-swk/P-STMO/assets/117512033/5dc906a1-1892-471d-a37a-754cae40474b">

Looking forward to your reply, thank you. @paTRICK-swk

**Comment by paTRICK-swk** [comment]
A simple way: use the average value as you said. A precise way: use the weighted average following this [document](https://github.com/paTRICK-swk/P-STMO/blob/aea43d0131e39d8a963598d88331f3f28055afee/3dhp_test/README.txt#L20).
