### ISSUE TITLE
可视化细节

### ISSUE THREAD

**Issue by qiqiApink** [paTRICK-swk/P-STMO#6]
请问训练的时候使用 tds=2，最后 inference 和可视化的时候使用 tds=1，这个对性能不会有影响吗？

**Comment by paTRICK-swk** [comment]
因为训练集是Human3.6M，其视频帧数是50fps，tds=2相当于将视频输入下采样到25fps；而大部分in-the-wild视频都是25fps，因此在inference的时候不再需要设置tds，这样能保证训练和测试的一致性。

**Comment by qiqiApink** [comment]
那如果测试视频也是50fps的话，是不是应该要对输入做跟训练时相同的处理

**Comment by paTRICK-swk** [comment]
> 那如果测试视频也是50fps的话，是不是应该要对输入做跟训练时相同的处理

是的
