### ISSUE TITLE
About the MPJPE of the PSTMOS_no_refine_48_5137_in_the_wild model ?

### ISSUE THREAD

**Issue by vicentowang** [paTRICK-swk/P-STMO#7]
according to the name of model file , MPJPE = 51.37 , is that right ?

**Comment by paTRICK-swk** [comment]
Yes

**Comment by vicentowang** [comment]
what is parameter of reverse_augmentation means ? thanks.  I got a problem that inference with test_augmentation make a distorted pose

**Comment by paTRICK-swk** [comment]
It flips the input sequence over the time domain for data augmentation, which is not used in our work. Please refer to the code snippet below:
https://github.com/paTRICK-swk/P-STMO/blob/be41b53bf8bb0a1391f8b71fd42615f820e5d83c/common/generator_tds.py#L122-L123
