### ISSUE TITLE
could you please release the training log and config for the model PSTMO_no_refine_11_4288_h36m_cpn

### ISSUE THREAD

**Issue by vicentowang** [paTRICK-swk/P-STMO#8]
thanks a lot.

**Comment by paTRICK-swk** [comment]
Sorry, for some reason I can't access the training log for the model with 42.88mm MPJPE at the moment. However, I can provide the log for the model with 43.06mm below.

> 2022/01/15 07:11:39 epoch: 1, lr: 0.0007000, loss: 0.1113, MPJPE: 53.73, p1: 49.43, p2: 38.68
2022/01/15 08:16:02 epoch: 2, lr: 0.0006790, loss: 0.0783, MPJPE: 38.89, p1: 47.14, p2: 37.27
2022/01/15 09:19:39 epoch: 3, lr: 0.0006586, loss: 0.0701, MPJPE: 35.28, p1: 46.11, p2: 36.31
2022/01/15 10:24:32 epoch: 4, lr: 0.0006389, loss: 0.0656, MPJPE: 33.28, p1: 45.22, p2: 35.63
2022/01/15 11:28:22 epoch: 5, lr: 0.0006197, loss: 0.0628, MPJPE: 31.94, p1: 45.23, p2: 35.83
2022/01/15 12:32:36 epoch: 6, lr: 0.0006011, loss: 0.0609, MPJPE: 31.00, p1: 44.29, p2: 35.17
2022/01/15 13:36:54 epoch: 7, lr: 0.0005831, loss: 0.0596, MPJPE: 30.35, p1: 44.24, p2: 35.26
2022/01/15 14:41:49 epoch: 8, lr: 0.0005656, loss: 0.0588, MPJPE: 29.91, p1: 44.05, p2: 35.30
2022/01/15 15:46:37 epoch: 9, lr: 0.0005486, loss: 0.0581, MPJPE: 29.56, p1: 43.65, p2: 34.74
2022/01/15 16:51:25 epoch: 10, lr: 0.0005322, loss: 0.0575, MPJPE: 29.26, p1: 44.04, p2: 34.81
2022/01/15 17:56:05 epoch: 11, lr: 0.0005162, loss: 0.0570, MPJPE: 29.01, p1: 43.41, p2: 34.88
2022/01/15 19:00:57 epoch: 12, lr: 0.0005007, loss: 0.0565, MPJPE: 28.81, p1: 43.91, p2: 34.73
2022/01/15 20:05:46 epoch: 13, lr: 0.0004857, loss: 0.0561, MPJPE: 28.57, p1: 44.07, p2: 35.13
2022/01/15 21:10:32 epoch: 14, lr: 0.0004711, loss: 0.0559, MPJPE: 28.46, p1: 43.46, p2: 34.85
2022/01/15 22:14:51 epoch: 15, lr: 0.0004570, loss: 0.0555, MPJPE: 28.28, p1: 43.88, p2: 34.70
2022/01/15 23:19:17 epoch: 16, lr: 0.0004433, loss: 0.0552, MPJPE: 28.13, p1: 43.37, p2: 34.85
2022/01/16 00:24:10 epoch: 17, lr: 0.0004300, loss: 0.0550, MPJPE: 28.04, p1: 43.95, p2: 34.82
2022/01/16 01:28:51 epoch: 18, lr: 0.0004171, loss: 0.0548, MPJPE: 27.92, p1: 43.79, p2: 34.78
2022/01/16 02:33:38 epoch: 19, lr: 0.0004046, loss: 0.0546, MPJPE: 27.82, p1: 43.70, p2: 35.12
2022/01/16 03:38:26 epoch: 20, lr: 0.0003924, loss: 0.0544, MPJPE: 27.70, p1: 43.30, p2: 34.94
2022/01/16 04:43:05 epoch: 21, lr: 0.0003807, loss: 0.0543, MPJPE: 27.67, p1: 43.61, p2: 34.99
2022/01/16 05:47:53 epoch: 22, lr: 0.0003692, loss: 0.0540, MPJPE: 27.52, p1: 43.51, p2: 34.86
2022/01/16 06:52:52 epoch: 23, lr: 0.0003582, loss: 0.0540, MPJPE: 27.50, p1: 43.53, p2: 34.85
2022/01/16 07:57:44 epoch: 24, lr: 0.0003474, loss: 0.0538, MPJPE: 27.41, p1: 43.49, p2: 34.80
2022/01/16 09:02:38 epoch: 25, lr: 0.0003370, loss: 0.0537, MPJPE: 27.34, p1: 43.75, p2: 34.75
2022/01/16 10:07:28 epoch: 26, lr: 0.0003269, loss: 0.0535, MPJPE: 27.28, p1: 43.41, p2: 34.64
2022/01/16 11:12:19 epoch: 27, lr: 0.0003171, loss: 0.0534, MPJPE: 27.20, p1: 43.91, p2: 34.92
2022/01/16 12:17:06 epoch: 28, lr: 0.0003076, loss: 0.0532, MPJPE: 27.17, p1: 43.07, p2: 34.61
2022/01/16 13:21:50 epoch: 29, lr: 0.0002983, loss: 0.0532, MPJPE: 27.12, p1: 43.43, p2: 34.81
2022/01/16 14:26:35 epoch: 30, lr: 0.0002894, loss: 0.0531, MPJPE: 27.07, p1: 43.66, p2: 34.83
2022/01/16 15:31:25 epoch: 31, lr: 0.0002807, loss: 0.0529, MPJPE: 26.99, p1: 43.57, p2: 34.90
2022/01/16 16:36:05 epoch: 32, lr: 0.0002723, loss: 0.0529, MPJPE: 26.99, p1: 43.68, p2: 34.86
2022/01/16 17:41:00 epoch: 33, lr: 0.0002641, loss: 0.0528, MPJPE: 26.93, p1: 43.67, p2: 34.81
2022/01/16 18:45:47 epoch: 34, lr: 0.0002562, loss: 0.0527, MPJPE: 26.88, p1: 43.15, p2: 34.65
2022/01/16 19:50:26 epoch: 35, lr: 0.0002485, loss: 0.0526, MPJPE: 26.86, p1: 43.68, p2: 35.00
2022/01/16 20:55:18 epoch: 36, lr: 0.0002411, loss: 0.0525, MPJPE: 26.81, p1: 43.57, p2: 34.99
2022/01/16 21:59:26 epoch: 37, lr: 0.0002338, loss: 0.0525, MPJPE: 26.77, p1: 43.22, p2: 34.52
2022/01/16 23:03:38 epoch: 38, lr: 0.0002268, loss: 0.0525, MPJPE: 26.77, p1: 43.50, p2: 34.86
2022/01/17 00:07:52 epoch: 39, lr: 0.0002200, loss: 0.0525, MPJPE: 26.77, p1: 43.25, p2: 34.56
2022/01/17 01:11:25 epoch: 40, lr: 0.0002134, loss: 0.0523, MPJPE: 26.70, p1: 43.60, p2: 34.78
2022/01/17 02:15:32 epoch: 41, lr: 0.0002070, loss: 0.0522, MPJPE: 26.64, p1: 43.61, p2: 34.93
2022/01/17 03:19:37 epoch: 42, lr: 0.0002008, loss: 0.0521, MPJPE: 26.61, p1: 43.73, p2: 34.97
2022/01/17 04:22:28 epoch: 43, lr: 0.0001948, loss: 0.0521, MPJPE: 26.62, p1: 43.54, p2: 34.69
2022/01/17 05:26:02 epoch: 44, lr: 0.0001889, loss: 0.0520, MPJPE: 26.57, p1: 43.42, p2: 34.90
2022/01/17 06:30:37 epoch: 45, lr: 0.0001833, loss: 0.0520, MPJPE: 26.55, p1: 43.53, p2: 34.71
2022/01/17 07:35:28 epoch: 46, lr: 0.0001778, loss: 0.0519, MPJPE: 26.52, p1: 43.77, p2: 34.98
2022/01/17 08:40:09 epoch: 47, lr: 0.0001724, loss: 0.0519, MPJPE: 26.51, p1: 43.92, p2: 35.05
2022/01/17 09:44:57 epoch: 48, lr: 0.0001673, loss: 0.0519, MPJPE: 26.49, p1: 43.50, p2: 34.73
2022/01/17 10:50:08 epoch: 49, lr: 0.0001622, loss: 0.0519, MPJPE: 26.51, p1: 43.07, p2: 34.68
2022/01/17 11:54:59 epoch: 50, lr: 0.0001574, loss: 0.0518, MPJPE: 26.46, p1: 43.55, p2: 34.76
2022/01/17 12:59:56 epoch: 51, lr: 0.0001526, loss: 0.0517, MPJPE: 26.43, p1: 43.52, p2: 34.81
2022/01/17 14:04:22 epoch: 52, lr: 0.0001481, loss: 0.0517, MPJPE: 26.40, p1: 43.26, p2: 34.79
2022/01/17 15:09:17 epoch: 53, lr: 0.0001436, loss: 0.0517, MPJPE: 26.38, p1: 43.12, p2: 34.63
2022/01/17 16:12:59 epoch: 54, lr: 0.0001393, loss: 0.0516, MPJPE: 26.38, p1: 43.26, p2: 34.82
2022/01/17 17:17:49 epoch: 55, lr: 0.0001351, loss: 0.0516, MPJPE: 26.35, p1: 43.43, p2: 34.59
2022/01/17 18:23:40 epoch: 56, lr: 0.0001311, loss: 0.0516, MPJPE: 26.34, p1: 43.42, p2: 34.94
2022/01/17 19:29:11 epoch: 57, lr: 0.0001271, loss: 0.0516, MPJPE: 26.34, p1: 43.54, p2: 34.76
2022/01/17 20:34:19 epoch: 58, lr: 0.0001233, loss: 0.0514, MPJPE: 26.25, p1: 43.48, p2: 34.85
2022/01/17 21:38:44 epoch: 59, lr: 0.0001196, loss: 0.0514, MPJPE: 26.29, p1: 43.27, p2: 34.72
